### PR TITLE
Command Class

### PR DESCRIPTION
**Pull request by arieldeveloper**
Adding a Command class for the use case to work off of. Its goal is to take in input data from the UI and then pass itself into a use case which then returns a Response that can be used again by the UI.

### CODE REVIEW

**Comment by arieldeveloper** [comment]
Haven't made this version of the command class extend the Map<String, String> yet.

**Comment by DerekCresswell** [comment]
@arieldeveloper Yeah make it extend that and that solves most of the problems. Just make sure that you DON'T use methods like `add_tags`. One, we aren't using underscores in this project (sadly). Two, the command does NOT need to know tags exist. The UI will fill these with whatever information they need, not only specific things.

**Review by DerekCresswell — CHANGES_REQUESTED** [review]
See other comment.

**Comment by arieldeveloper** [comment]
Just made it extend the map. A simple interface for now.

**Pull request closed without merging**
